Lab 3
================

``` r
knitr::opts_chunk$set(
        echo = TRUE,
        warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() +theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

``` r
SIR=function(t,state,parameters){
  with(as.list(c(state,parameters)),{
    # rate of change
    dS = -beta*S*I/N;
    dI= beta*S*I/N - gamma*I;
    dR = gamma*I;
    
    # return the rate of change
    list(c(dS, dI, dR))
  }) # end with(as.list...)
}
```

``` r
N=1e5; # population size
I0=10; # initial No. of Infectious people
S0=N-I0;  # initial No. of Susceptible people
R0=N-I0-S0 # initial No. of Recovered people
state=c(S=S0, I=I0, R=R0);  # store the initial conditions I & S together 
parameters=c(beta=.5,gamma=.3);  # store the model parameters, unit: per day
```

# Part 1: Find the final epidemic size using simulation

## Question 1

Compute and plot R over time for the following epidemic setting. What is
the final epidemic size (i.e. R at the end of the epidemic)?

``` r
beta=.5; gamma=.3;
parameters=c(beta=beta,gamma=gamma)
times=seq(0,365,by=1)  # run for a year
state=c(S=S0,I=I0, R=R0)
sim=ode(y=state,times=times,func=SIR,parms=parameters)
```

``` r
q1_susceptible = ggplot(sim, aes(x = time, y = S, color = time)) +
  geom_point() +
  geom_line() +
  labs(title = "Susceptible Over Time", 
       x = "Day", 
       y = "Number of People Susceptible") +
  theme_minimal()
```

``` r
q1_infectious = ggplot(sim, aes(x = time, y = I, color = time)) +
  geom_point() +
  geom_line() +
  labs(title = "Infectious Over Time", 
       x = "Day", 
       y = "Number of People Infectious") +
  theme_minimal()
```

``` r
q1_recovered = ggplot(sim, aes(x = time, y = R, color = time)) +
  geom_point() +
  geom_line() +
  labs(title = "Recovered Over Time", 
       x = "Day", 
       y = "Number of People Recovered") +
  theme_minimal()
```

``` r
q1_model = q1_susceptible + q1_infectious + q1_recovered

q1_model
```

<img src="Homework-3_files/figure-gfm/unnamed-chunk-8-1.png" width="90%" />

``` r
sim_df = as.data.frame(sim)
return(sim_df)
```

    ##     time        S            I            R
    ## 1      0 99990.00 1.000000e+01     0.000000
    ## 2      1 99984.47 1.221325e+01     3.320940
    ## 3      2 99977.71 1.491590e+01     7.376829
    ## 4      3 99969.45 1.821593e+01    12.330141
    ## 5      4 99959.38 2.224505e+01    18.379199
    ## 6      5 99947.07 2.716384e+01    25.766022
    ## 7      6 99932.05 3.316801e+01    34.785919
    ## 8      7 99913.71 4.049594e+01    45.799044
    ## 9      8 99891.32 4.943784e+01    59.244662
    ## 10     9 99864.00 6.034673e+01    75.658203
    ## 11    10 99830.66 7.365162e+01    95.692015
    ## 12    11 99789.99 8.987333e+01   120.140510
    ## 13    12 99740.39 1.096432e+02   149.970408
    ## 14    13 99679.92 1.337252e+02   186.357135
    ## 15    14 99606.23 1.630421e+02   230.728425
    ## 16    15 99516.48 1.987053e+02   284.816318
    ## 17    16 99407.23 2.420492e+02   350.718822
    ## 18    17 99274.36 2.946699e+02   430.972517
    ## 19    18 99112.90 3.584670e+02   528.637256
    ## 20    19 98916.92 4.356882e+02   647.393861
    ## 21    20 98679.37 5.289725e+02   791.655079
    ## 22    21 98391.92 6.413897e+02   966.689118
    ## 23    22 98044.78 7.764684e+02  1178.753450
    ## 24    23 97626.56 9.382030e+02  1435.234163
    ## 25    24 97124.19 1.131027e+03  1744.782720
    ## 26    25 96522.83 1.359732e+03  2117.437262
    ## 27    26 95805.97 1.629317e+03  2564.709556
    ## 28    27 94955.66 1.944733e+03  3099.611418
    ## 29    28 93952.91 2.310499e+03  3736.586543
    ## 30    29 92778.51 2.730180e+03  4491.306535
    ## 31    30 91414.01 3.205704e+03  5380.285720
    ## 32    31 89843.17 3.736554e+03  6420.271593
    ## 33    32 88053.72 4.318895e+03  7627.380582
    ## 34    33 86039.27 4.944751e+03  9015.976224
    ## 35    34 83801.25 5.601421e+03 10597.330775
    ## 36    35 81350.52 6.271309e+03 12378.168810
    ## 37    36 78708.34 6.932403e+03 14359.252827
    ## 38    37 75906.31 7.559475e+03 16534.219124
    ## 39    38 72985.10 8.126010e+03 18888.886564
    ## 40    39 69992.15 8.606622e+03 21401.224562
    ## 41    40 66978.32 8.979599e+03 24042.076747
    ## 42    41 63994.27 9.229118e+03 26776.609288
    ## 43    42 61086.96 9.346717e+03 29566.321032
    ## 44    43 58296.84 9.331805e+03 32371.353760
    ## 45    44 55656.03 9.191171e+03 35152.802216
    ## 46    45 53187.56 8.937692e+03 37874.750817
    ## 47    46 50905.60 8.588562e+03 40505.841761
    ## 48    47 48816.36 8.163361e+03 43020.280070
    ## 49    48 46919.44 7.682281e+03 45398.277210
    ## 50    49 45209.32 7.164673e+03 47626.007150
    ## 51    50 43676.79 6.628019e+03 49695.189561
    ## 52    51 42310.26 6.087314e+03 51602.426521
    ## 53    52 41096.79 5.554805e+03 53348.409365
    ## 54    53 40022.91 5.040004e+03 54937.090441
    ## 55    54 39075.23 4.549886e+03 56374.888431
    ## 56    55 38240.84 4.089193e+03 57669.971007
    ## 57    56 37507.57 3.660789e+03 58831.637868
    ## 58    57 36864.17 3.266022e+03 59869.811654
    ## 59    58 36300.31 2.905056e+03 60794.633709
    ## 60    59 35806.67 2.577172e+03 61616.155228
    ## 61    60 35374.87 2.281020e+03 62344.111159
    ## 62    61 34997.41 2.014824e+03 62987.763174
    ## 63    62 34667.65 1.776555e+03 63555.798486
    ## 64    63 34379.68 1.564049e+03 64056.272439
    ## 65    64 34128.31 1.375110e+03 64496.584464
    ## 66    65 33908.95 1.207576e+03 64883.478643
    ## 67    66 33717.57 1.059366e+03 65223.061785
    ## 68    67 33550.65 9.285150e+02 65520.833376
    ## 69    68 33405.08 8.131923e+02 65781.723028
    ## 70    69 33278.16 7.117086e+02 66010.132125
    ## 71    70 33167.50 6.225204e+02 66209.977218
    ## 72    71 33071.04 5.442274e+02 66384.733405
    ## 73    72 32986.96 4.755668e+02 66537.476475
    ## 74    73 32913.67 4.154054e+02 66670.923017
    ## 75    74 32849.80 3.627304e+02 66787.467979
    ## 76    75 32794.14 3.166403e+02 66889.219417
    ## 77    76 32745.63 2.763348e+02 66978.030337
    ## 78    77 32703.37 2.411052e+02 67055.527628
    ## 79    78 32666.54 2.103254e+02 67123.138198
    ## 80    79 32634.44 1.834435e+02 67182.112450
    ## 81    80 32606.48 1.599734e+02 67233.545277
    ## 82    81 32582.12 1.394878e+02 67278.394757
    ## 83    82 32560.89 1.216118e+02 67317.498775
    ## 84    83 32542.39 1.060161e+02 67351.589724
    ## 85    84 32526.28 9.241244e+01 67381.307514
    ## 86    85 32512.24 8.054831e+01 67407.211038
    ## 87    86 32500.01 7.020272e+01 67429.788264
    ## 88    87 32489.35 6.118241e+01 67449.465119
    ## 89    88 32480.07 5.331847e+01 67466.613280
    ## 90    89 32471.98 4.646328e+01 67481.557017
    ## 91    90 32464.93 4.048795e+01 67494.579183
    ## 92    91 32458.79 3.527989e+01 67505.926468
    ## 93    92 32453.45 3.074089e+01 67515.813985
    ## 94    93 32448.79 2.678518e+01 67524.429295
    ## 95    94 32444.73 2.333799e+01 67531.935914
    ## 96    95 32441.19 2.033405e+01 67538.476386
    ## 97    96 32438.11 1.771647e+01 67544.174958
    ## 98    97 32435.42 1.543563e+01 67549.139925
    ## 99    98 32433.09 1.344826e+01 67553.465668
    ## 100   99 32431.05 1.171664e+01 67557.234441
    ## 101  100 32429.27 1.020789e+01 67560.517925
    ## 102  101 32427.73 8.893344e+00 67563.378582
    ## 103  102 32426.38 7.748027e+00 67565.870844
    ## 104  103 32425.21 6.750166e+00 67568.042136
    ## 105  104 32424.19 5.880787e+00 67569.933784
    ## 106  105 32423.29 5.123354e+00 67571.581796
    ## 107  106 32422.52 4.463457e+00 67573.017544
    ## 108  107 32421.84 3.888543e+00 67574.268363
    ## 109  108 32421.25 3.387670e+00 67575.358069
    ## 110  109 32420.74 2.951304e+00 67576.307412
    ## 111  110 32420.29 2.571141e+00 67577.134469
    ## 112  111 32419.91 2.239942e+00 67577.854990
    ## 113  112 32419.57 1.951403e+00 67578.482698
    ## 114  113 32419.27 1.700030e+00 67579.029546
    ## 115  114 32419.01 1.481036e+00 67579.505951
    ## 116  115 32418.79 1.290250e+00 67579.920987
    ## 117  116 32418.59 1.124040e+00 67580.282558
    ## 118  117 32418.42 9.792405e-01 67580.597551
    ## 119  118 32418.27 8.530934e-01 67580.871966
    ## 120  119 32418.15 7.431962e-01 67581.111031
    ## 121  120 32418.03 6.474558e-01 67581.319299
    ## 122  121 32417.94 5.640486e-01 67581.500737
    ## 123  122 32417.85 4.913859e-01 67581.658802
    ## 124  123 32417.78 4.280837e-01 67581.796504
    ## 125  124 32417.71 3.729363e-01 67581.916467
    ## 126  125 32417.65 3.248930e-01 67582.020976
    ## 127  126 32417.60 2.830388e-01 67582.112021
    ## 128  127 32417.56 2.465764e-01 67582.191338
    ## 129  128 32417.52 2.148112e-01 67582.260436
    ## 130  129 32417.49 1.871382e-01 67582.320633
    ## 131  130 32417.46 1.630301e-01 67582.373076
    ## 132  131 32417.44 1.420277e-01 67582.418762
    ## 133  132 32417.42 1.237309e-01 67582.458563
    ## 134  133 32417.40 1.077912e-01 67582.493236
    ## 135  134 32417.38 9.390493e-02 67582.523443
    ## 136  135 32417.37 8.180757e-02 67582.549758
    ## 137  136 32417.36 7.126865e-02 67582.572683
    ## 138  137 32417.35 6.208741e-02 67582.592655
    ## 139  138 32417.34 5.408895e-02 67582.610053
    ## 140  139 32417.33 4.712090e-02 67582.625211
    ## 141  140 32417.32 4.105051e-02 67582.638416
    ## 142  141 32417.31 3.576214e-02 67582.649919
    ## 143  142 32417.31 3.115505e-02 67582.659941
    ## 144  143 32417.30 2.714147e-02 67582.668672
    ## 145  144 32417.30 2.364495e-02 67582.676278
    ## 146  145 32417.30 2.059887e-02 67582.682904
    ## 147  146 32417.29 1.794520e-02 67582.688676
    ## 148  147 32417.29 1.563339e-02 67582.693705
    ## 149  148 32417.29 1.361941e-02 67582.698086
    ## 150  149 32417.29 1.186488e-02 67582.701903
    ## 151  150 32417.28 1.033637e-02 67582.705227
    ## 152  151 32417.28 9.004780e-03 67582.708124
    ## 153  152 32417.28 7.844731e-03 67582.710647
    ## 154  153 32417.28 6.834126e-03 67582.712846
    ## 155  154 32417.28 5.953714e-03 67582.714761
    ## 156  155 32417.28 5.186721e-03 67582.716429
    ## 157  156 32417.28 4.518537e-03 67582.717883
    ## 158  157 32417.28 3.936432e-03 67582.719149
    ## 159  158 32417.28 3.429317e-03 67582.720252
    ## 160  159 32417.28 2.987532e-03 67582.721213
    ## 161  160 32417.28 2.602661e-03 67582.722050
    ## 162  161 32417.27 2.267370e-03 67582.722780
    ## 163  162 32417.27 1.975274e-03 67582.723415
    ## 164  163 32417.27 1.720808e-03 67582.723969
    ## 165  164 32417.27 1.499123e-03 67582.724451
    ## 166  165 32417.27 1.305997e-03 67582.724871
    ## 167  166 32417.27 1.137751e-03 67582.725237
    ## 168  167 32417.27 9.911785e-04 67582.725556
    ## 169  168 32417.27 8.634878e-04 67582.725834
    ## 170  169 32417.27 7.522470e-04 67582.726076
    ## 171  170 32417.27 6.553372e-04 67582.726286
    ## 172  171 32417.27 5.709119e-04 67582.726470
    ## 173  172 32417.27 4.973629e-04 67582.726630
    ## 174  173 32417.27 4.332891e-04 67582.726769
    ## 175  174 32417.27 3.774697e-04 67582.726891
    ## 176  175 32417.27 3.288413e-04 67582.726997
    ## 177  176 32417.27 2.864776e-04 67582.727089
    ## 178  177 32417.27 2.495715e-04 67582.727169
    ## 179  178 32417.27 2.174199e-04 67582.727239
    ## 180  179 32417.27 1.894103e-04 67582.727300
    ## 181  180 32417.27 1.650078e-04 67582.727353
    ## 182  181 32417.27 1.437515e-04 67582.727399
    ## 183  182 32417.27 1.252338e-04 67582.727439
    ## 184  183 32417.27 1.091021e-04 67582.727475
    ## 185  184 32417.27 9.504825e-05 67582.727505
    ## 186  185 32417.27 8.280474e-05 67582.727532
    ## 187  186 32417.27 7.213836e-05 67582.727555
    ## 188  187 32417.27 6.284596e-05 67582.727575
    ## 189  188 32417.27 5.475054e-05 67582.727593
    ## 190  189 32417.27 4.769793e-05 67582.727608
    ## 191  190 32417.27 4.155378e-05 67582.727622
    ## 192  191 32417.27 3.620109e-05 67582.727633
    ## 193  192 32417.27 3.152987e-05 67582.727643
    ## 194  193 32417.27 2.747492e-05 67582.727652
    ## 195  194 32417.27 2.393027e-05 67582.727660
    ## 196  195 32417.27 2.084311e-05 67582.727667
    ## 197  196 32417.27 1.815427e-05 67582.727672
    ## 198  197 32417.27 1.581231e-05 67582.727678
    ## 199  198 32417.27 1.377247e-05 67582.727682
    ## 200  199 32417.27 1.199577e-05 67582.727686
    ## 201  200 32417.27 1.044827e-05 67582.727689
    ## 202  201 32417.27 9.100409e-06 67582.727692
    ## 203  202 32417.27 7.926425e-06 67582.727695
    ## 204  203 32417.27 6.903888e-06 67582.727697
    ## 205  204 32417.27 6.013262e-06 67582.727699
    ## 206  205 32417.27 5.237530e-06 67582.727701
    ## 207  206 32417.27 4.561870e-06 67582.727702
    ## 208  207 32417.27 3.973373e-06 67582.727703
    ## 209  208 32417.27 3.460794e-06 67582.727704
    ## 210  209 32417.27 3.014339e-06 67582.727705
    ## 211  210 32417.27 2.625479e-06 67582.727706
    ## 212  211 32417.27 2.286783e-06 67582.727707
    ## 213  212 32417.27 1.991780e-06 67582.727708
    ## 214  213 32417.27 1.734833e-06 67582.727708
    ## 215  214 32417.27 1.511034e-06 67582.727709
    ## 216  215 32417.27 1.316105e-06 67582.727709
    ## 217  216 32417.27 1.146323e-06 67582.727709
    ## 218  217 32417.27 9.984432e-07 67582.727710
    ## 219  218 32417.27 8.696405e-07 67582.727710
    ## 220  219 32417.27 7.574539e-07 67582.727710
    ## 221  220 32417.27 6.597396e-07 67582.727710
    ## 222  221 32417.27 5.746309e-07 67582.727711
    ## 223  222 32417.27 5.005015e-07 67582.727711
    ## 224  223 32417.27 4.359351e-07 67582.727711
    ## 225  224 32417.27 3.796979e-07 67582.727711
    ## 226  225 32417.27 3.307155e-07 67582.727711
    ## 227  226 32417.27 2.880521e-07 67582.727711
    ## 228  227 32417.27 2.508923e-07 67582.727711
    ## 229  228 32417.27 2.185263e-07 67582.727711
    ## 230  229 32417.27 1.903357e-07 67582.727711
    ## 231  230 32417.27 1.657817e-07 67582.727712
    ## 232  231 32417.27 1.443953e-07 67582.727712
    ## 233  232 32417.27 1.257678e-07 67582.727712
    ## 234  233 32417.27 1.095433e-07 67582.727712
    ## 235  234 32417.27 9.541183e-08 67582.727712
    ## 236  235 32417.27 8.310337e-08 67582.727712
    ## 237  236 32417.27 7.238274e-08 67582.727712
    ## 238  237 32417.27 6.304511e-08 67582.727712
    ## 239  238 32417.27 5.490447e-08 67582.727712
    ## 240  239 32417.27 4.779636e-08 67582.727712
    ## 241  240 32417.27 4.132131e-08 67582.727712
    ## 242  241 32417.27 3.631322e-08 67582.727712
    ## 243  242 32417.27 3.191211e-08 67582.727712
    ## 244  243 32417.27 2.804440e-08 67582.727712
    ## 245  244 32417.27 2.464546e-08 67582.727712
    ## 246  245 32417.27 2.165846e-08 67582.727712
    ## 247  246 32417.27 1.903348e-08 67582.727712
    ## 248  247 32417.27 1.672665e-08 67582.727712
    ## 249  248 32417.27 1.469940e-08 67582.727712
    ## 250  249 32417.27 1.291785e-08 67582.727712
    ## 251  250 32417.27 1.135223e-08 67582.727712
    ## 252  251 32417.27 9.976352e-09 67582.727712
    ## 253  252 32417.27 8.767231e-09 67582.727712
    ## 254  253 32417.27 7.704654e-09 67582.727712
    ## 255  254 32417.27 6.770860e-09 67582.727712
    ## 256  255 32417.27 5.950241e-09 67582.727712
    ## 257  256 32417.27 5.229079e-09 67582.727712
    ## 258  257 32417.27 4.595322e-09 67582.727712
    ## 259  258 32417.27 4.038375e-09 67582.727712
    ## 260  259 32417.27 3.548929e-09 67582.727712
    ## 261  260 32417.27 3.118804e-09 67582.727712
    ## 262  261 32417.27 2.740809e-09 67582.727712
    ## 263  262 32417.27 2.408626e-09 67582.727712
    ## 264  263 32417.27 2.116704e-09 67582.727712
    ## 265  264 32417.27 1.860162e-09 67582.727712
    ## 266  265 32417.27 1.634713e-09 67582.727712
    ## 267  266 32417.27 1.436588e-09 67582.727712
    ## 268  267 32417.27 1.262475e-09 67582.727712
    ## 269  268 32417.27 1.109465e-09 67582.727712
    ## 270  269 32417.27 9.749993e-10 67582.727712
    ## 271  270 32417.27 8.568307e-10 67582.727712
    ## 272  271 32417.27 7.529839e-10 67582.727712
    ## 273  272 32417.27 6.617232e-10 67582.727712
    ## 274  273 32417.27 5.815233e-10 67582.727712
    ## 275  274 32417.27 5.110434e-10 67582.727712
    ## 276  275 32417.27 4.491056e-10 67582.727712
    ## 277  276 32417.27 3.946746e-10 67582.727712
    ## 278  277 32417.27 3.468406e-10 67582.727712
    ## 279  278 32417.27 3.048039e-10 67582.727712
    ## 280  279 32417.27 2.678621e-10 67582.727712
    ## 281  280 32417.27 2.353976e-10 67582.727712
    ## 282  281 32417.27 2.068677e-10 67582.727712
    ## 283  282 32417.27 1.817956e-10 67582.727712
    ## 284  283 32417.27 1.597622e-10 67582.727712
    ## 285  284 32417.27 1.403992e-10 67582.727712
    ## 286  285 32417.27 1.233830e-10 67582.727712
    ## 287  286 32417.27 1.084292e-10 67582.727712
    ## 288  287 32417.27 9.528770e-11 67582.727712
    ## 289  288 32417.27 8.373896e-11 67582.727712
    ## 290  289 32417.27 7.358990e-11 67582.727712
    ## 291  290 32417.27 6.467091e-11 67582.727712
    ## 292  291 32417.27 5.683288e-11 67582.727712
    ## 293  292 32417.27 4.994481e-11 67582.727712
    ## 294  293 32417.27 4.389156e-11 67582.727712
    ## 295  294 32417.27 3.857196e-11 67582.727712
    ## 296  295 32417.27 3.389709e-11 67582.727712
    ## 297  296 32417.27 2.978881e-11 67582.727712
    ## 298  297 32417.27 2.617844e-11 67582.727712
    ## 299  298 32417.27 2.300565e-11 67582.727712
    ## 300  299 32417.27 2.021740e-11 67582.727712
    ## 301  300 32417.27 1.776707e-11 67582.727712
    ## 302  301 32417.27 1.561373e-11 67582.727712
    ## 303  302 32417.27 1.372136e-11 67582.727712
    ## 304  303 32417.27 1.205835e-11 67582.727712
    ## 305  304 32417.27 1.059690e-11 67582.727712
    ## 306  305 32417.27 9.312567e-12 67582.727712
    ## 307  306 32417.27 8.183896e-12 67582.727712
    ## 308  307 32417.27 7.192018e-12 67582.727712
    ## 309  308 32417.27 6.320355e-12 67582.727712
    ## 310  309 32417.27 5.554337e-12 67582.727712
    ## 311  310 32417.27 4.881158e-12 67582.727712
    ## 312  311 32417.27 4.289568e-12 67582.727712
    ## 313  312 32417.27 3.769678e-12 67582.727712
    ## 314  313 32417.27 3.312798e-12 67582.727712
    ## 315  314 32417.27 2.911291e-12 67582.727712
    ## 316  315 32417.27 2.558447e-12 67582.727712
    ## 317  316 32417.27 2.248366e-12 67582.727712
    ## 318  317 32417.27 1.975867e-12 67582.727712
    ## 319  318 32417.27 1.736395e-12 67582.727712
    ## 320  319 32417.27 1.525946e-12 67582.727712
    ## 321  320 32417.27 1.341003e-12 67582.727712
    ## 322  321 32417.27 1.178475e-12 67582.727712
    ## 323  322 32417.27 1.035646e-12 67582.727712
    ## 324  323 32417.27 9.101269e-13 67582.727712
    ## 325  324 32417.27 7.998207e-13 67582.727712
    ## 326  325 32417.27 7.028835e-13 67582.727712
    ## 327  326 32417.27 6.176949e-13 67582.727712
    ## 328  327 32417.27 5.428311e-13 67582.727712
    ## 329  328 32417.27 4.770407e-13 67582.727712
    ## 330  329 32417.27 4.192240e-13 67582.727712
    ## 331  330 32417.27 3.684146e-13 67582.727712
    ## 332  331 32417.27 3.237632e-13 67582.727712
    ## 333  332 32417.27 2.845236e-13 67582.727712
    ## 334  333 32417.27 2.500397e-13 67582.727712
    ## 335  334 32417.27 2.197352e-13 67582.727712
    ## 336  335 32417.27 1.931036e-13 67582.727712
    ## 337  336 32417.27 1.696997e-13 67582.727712
    ## 338  337 32417.27 1.491323e-13 67582.727712
    ## 339  338 32417.27 1.310577e-13 67582.727712
    ## 340  339 32417.27 1.151736e-13 67582.727712
    ## 341  340 32417.27 1.012147e-13 67582.727712
    ## 342  341 32417.27 8.894765e-14 67582.727712
    ## 343  342 32417.27 7.816732e-14 67582.727712
    ## 344  343 32417.27 6.869354e-14 67582.727712
    ## 345  344 32417.27 6.036797e-14 67582.727712
    ## 346  345 32417.27 5.305145e-14 67582.727712
    ## 347  346 32417.27 4.662169e-14 67582.727712
    ## 348  347 32417.27 4.097120e-14 67582.727712
    ## 349  348 32417.27 3.600554e-14 67582.727712
    ## 350  349 32417.27 3.164172e-14 67582.727712
    ## 351  350 32417.27 2.780678e-14 67582.727712
    ## 352  351 32417.27 2.443664e-14 67582.727712
    ## 353  352 32417.27 2.147495e-14 67582.727712
    ## 354  353 32417.27 1.887221e-14 67582.727712
    ## 355  354 32417.27 1.658493e-14 67582.727712
    ## 356  355 32417.27 1.457486e-14 67582.727712
    ## 357  356 32417.27 1.280840e-14 67582.727712
    ## 358  357 32417.27 1.125604e-14 67582.727712
    ## 359  358 32417.27 9.891823e-15 67582.727712
    ## 360  359 32417.27 8.692947e-15 67582.727712
    ## 361  360 32417.27 7.639374e-15 67582.727712
    ## 362  361 32417.27 6.713492e-15 67582.727712
    ## 363  362 32417.27 5.899825e-15 67582.727712
    ## 364  363 32417.27 5.184774e-15 67582.727712
    ## 365  364 32417.27 4.556386e-15 67582.727712
    ## 366  365 32417.27 4.004158e-15 67582.727712

``` r
sim_df$week = ceiling(sim_df$time / 7)

weekly_data = sim_df |> 
  group_by(week) |> 
  summarize(
    S_weekly = mean(S),
    I_weekly = mean(I),
    R_weekly = mean(R)
  )
```

The final epidemic size or R at the end of the epidemic is 67582.73.

# Part 2: Test the epidemic threshold

## Question 2

What are the differences among the simulations? Explain what you see.

``` r
run_simulation = function(beta, gamma) {
  parameters = c(beta = beta, gamma = gamma)
  state = c(S = S0, I = I0, R = R0)
  
  sim = ode(y = state, times = times, func = SIR, parms = parameters)
  
  sim_df = as.data.frame(sim)
  return(sim_df)
}


params_list = list(
  list(beta = 0.5, gamma = 0.3), 
  list(beta = 0.5, gamma = 0.4), 
  list(beta = 0.5, gamma = 0.5), 
  list(beta = 0.5, gamma = 0.6)
)

simulations = lapply(params_list, function(params) {
  run_simulation(params$beta, params$gamma)
})
```

``` r
plot_list = lapply(1:length(simulations), function(i) {
  sim_df = simulations [[i]]
  ggplot(sim_df, aes(x = time, y = I)) +
    geom_line() +
    labs(title = paste("Infectious Population Over Time\n(beta =", params_list[[i]]$beta, "gamma =", params_list[[i]]$gamma), 
         x = "Day", 
         y = "Number of Infectious People") +
    theme_minimal()
})
```

``` r
plot_list[[1]] + plot_list[[2]] + plot_list[[3]] + plot_list[[4]]
```

<img src="Homework-3_files/figure-gfm/unnamed-chunk-12-1.png" width="90%" />

When the gamma is smaller ot R0 is larger, the epidemic curve grows more
quickly and has a larger peak, leading to faster transmission. When the
gamma is larger or R0 is smaller, the epidemic curve grows slowly and
has a lower peak, leading to slower transmission.

When gamma increases from 0.3 to 0.4, the peak of the curve is slightly
lower. Where gamma is 0.5, the curve appears almost linear in the
negative direction. Where gamma is 0.6. the epidemic curve is negatively
exponential with no significant peak.

# Part 3: Test the exponential period

## Question 3

Plot log(I) vs t (try t=3 to 8 weeks) and see when the exponential
period ends.

``` r
beta=.5; gamma=.3;
parameters=c(beta=beta,gamma=gamma)
times=seq(0,100,by=1) 
state=c(S=S0,I=I0, R=R0)
sim=ode(y=state,times=times,func=SIR,parms=parameters)
```

``` r
subset_sim = sim_df |> 
  filter(time >= 21 & time <= 56)
```

``` r
subset_sim$log_I = log(subset_sim$I)
```

``` r
log_infectious = ggplot(subset_sim, aes(x = time, y = log_I)) +
  geom_point() +
  geom_line() +
  labs(
    title = "Log(I) Over Time (3 to 8 Weeks)", 
    x = "Day", 
    y = "Log (Number of Infectious People") +
  theme_minimal()

log_infectious
```

<img src="Homework-3_files/figure-gfm/unnamed-chunk-16-1.png" width="90%" />

The exponential period ends when the curve reaches its peak at around
Day 42. At this point, growth rate begins to slow down and number of
infectious people begins to decrease or decline.

## Question 4

Fit log(I) to t over the exponential period, and find the slope of the
linear regression. What does the slope represent?

``` r
exp_growth = subset_sim |> 
  filter(time>= 21 & time <= 49)
```

``` r
exp_growth_lm = lm(log_I ~ time, data = exp_growth)
```

``` r
slope = coef(exp_growth_lm) [2]

slope
```

    ##       time 
    ## 0.09227904

``` r
exp_growth_plot = ggplot(exp_growth, aes(x = time, y = log_I)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  labs(title = "Log(I) vs Time (Exponential Period)", 
       x = "Day", 
       y = "Log (Number of Infectious People)") +
  theme_minimal()

exp_growth_plot
```

    ## `geom_smooth()` using formula = 'y ~ x'

<img src="Homework-3_files/figure-gfm/unnamed-chunk-20-1.png" width="90%" />

The slope of the linear regression is 0.0923. The slope represents the
exponential growth rate or transmission rate (beta) of the infectious
population, indicating how quickly the disease spreads.

# Part 4: Epidemic burnout

## Question 5

Show your results and check the final S and I (is S=0? is I=0). Why does
the epidemic die out eventually?

``` r
beta=.5; gamma=.3;
parameters=c(beta=beta,gamma=gamma)
times=seq(0,600,by=1) 
state=c(S=S0,I=I0, R=R0)
sim=ode(y=state,times=times,func=SIR,parms=parameters)
```

``` r
q5_susceptible = ggplot(sim, aes(x = time, y = S, color = time)) +
  geom_point() +
  geom_line() +
  labs(title = "Susceptible Over Time", 
       x = "Day", 
       y = "Number of People Susceptible") +
  theme_minimal()
```

``` r
q5_infectious = ggplot(sim, aes(x = time, y = I, color = time)) +
  geom_point() +
  geom_line() +
  labs(title = "Infectious Over Time", 
       x = "Day", 
       y = "Number of People Infectious") +
  theme_minimal()
```

``` r
q5_recovered = ggplot(sim, aes(x = time, y = R, color = time)) +
  geom_point() +
  geom_line() +
  labs(title = "Recovered Over Time", 
       x = "Day", 
       y = "Number of People Recovered") +
  theme_minimal()
```

``` r
q5_model = q5_susceptible + q5_infectious + q5_recovered

q5_model
```

<img src="Homework-3_files/figure-gfm/unnamed-chunk-25-1.png" width="90%" />

Over time, by day 600, the number of individuals that are susceptible
and infectious drops to 0. Therefore, the transmission rate drops as
fewer individuals can contract the disease.
